LANGUAGES = {
    '0': 'afrikaans',
    '1': 'albanian',
    '2': 'amharic',
    '3': 'arabic',
    '4': 'armenian',
    '5': 'azerbaijani',
    '6': 'basque',
    '7': 'belarusian',
    '8': 'bengali',
    '9': 'bosnian',
    '10': 'bulgarian',
    '11': 'catalan',
    '12': 'cebuano',
    '13': 'chichewa',
    '14': 'chinese (simplified)',
    '15': 'chinese (traditional)',
    '16': 'corsican',
    '17': 'croatian',
    '18': 'czech',
    '19': 'danish',
    '20': 'dutch',
    '21': 'english',
    '22': 'esperanto',
    '23': 'estonian',
    '24': 'filipino',
    '25': 'finnish',
    '26': 'french',
    '27': 'frisian',
    '28': 'galician',
    '29': 'georgian',
    '30': 'german',
    '31': 'greek',
    '32': 'gujarati',
    '33': 'haitian creole',
    '34': 'hausa',
    '35': 'hawaiian',
    '36': 'hebrew',
    '37': 'hebrew',
    '38': 'hindi',
    '39': 'hmong',
    '40': 'hungarian',
    '41': 'icelandic',
    '42': 'igbo',
    '43': 'indonesian',
    '44': 'irish',
    '45': 'italian',
    '46': 'japanese',
    '47': 'javanese',
    '48': 'kannada',
    '49': 'kazakh',
    '50': 'khmer',
    '51': 'korean',
    '52': 'kurdish (kurmanji)',
    '53': 'kyrgyz',
    '54': 'lao',
    '55': 'latin',
    '56': 'latvian',
    '57': 'lithuanian',
    '58': 'luxembourgish',
    '59': 'macedonian',
    '60': 'malagasy',
    '61': 'malay',
    '62': 'malayalam',
    '63': 'maltese',
    '64': 'maori',
    '65': 'marathi',
    '66': 'mongolian',
    '67': 'myanmar (burmese)',
    '68': 'nepali',
    '69': 'norwegian',
    '70': 'odia',
    '71': 'pashto',
    '72': 'persian',
    '73': 'polish',
    '74': 'portuguese',
    '75': 'punjabi',
    '76': 'romanian',
    '77': 'russian',
    '78': 'samoan',
    '79': 'scots gaelic',
    '80': 'serbian',
    '81': 'sesotho',
    '82': 'shona',
    '83': 'sindhi',
    '84': 'sinhala',
    '85': 'slovak',
    '86': 'slovenian',
    '87': 'somali',
    '88': 'spanish',
    '89': 'sundanese',
    '90': 'swahili',
    '91': 'swedish',
    '92': 'tajik',
    '93': 'tamil',
    '94': 'telugu',
    '95': 'thai',
    '96': 'turkish',
    '97': 'ukrainian',
    '98': 'urdu',
    '99': 'uyghur',
    '100': 'uzbek',
    '101': 'vietnamese',
    '102': 'welsh',
    '103': 'xhosa',
    '104': 'yiddish',
    '105': 'yoruba',
    '106': 'zulu',
}


def discord_msg():
    discord_response = ''
    for key in LANGUAGES:
        try:
            discord_response += f'{LANGUAGES[key]}\n'
        except KeyError:
            return
    return discord_response
