#! /bin/bash

mkdir tmp
pip3 install discord
pip3 install python-dotenv
pip3 install google
pip3 install robin-stocks
pip3 install wolframclient
pip3 install googletrans
sudo apt install ffmpeg -y
pip3 install ffmpeg
pip3 install ffmpeg-python
sudo snap install ffmpeg